project_name: "my-awesome-project"
language: typescript  # python, rust, go, java など
entry_points:
  - src/index.ts
  - src/app.ts
ignored_dirs:
  - .claude
  - .github
  - .serena
  - .vscode
  - assets
  - db
  - source
  - dowonloads
  - local_docker
  - release/app/node_modules
  - release/app/dist
  - release/build
  - release/db
  - src/node_modules
  - node_modules
  - .erb/node_modules
  - .erb/dll
  - .git
  - dist
  - coverage
  - __pycache__
  - public/images  # 画像ディレクトリを除外
  - docs/pdfs      # PDFドキュメントを除外
ignored_files:
  - "*.log"
  - "*.tmp"
  - ".env*"
  - "*.jpg"
  - "*.png"
  - "*.pdf"
  - "*.zip"
# max_file_size: 1048576  # 1MB（バイナリも含む総バイト数）
show_logs: true
use_lsp: true
# セキュリティ設定
security:
  exclude_sensitive:
    - "**/*.key"
    - "**/*.pem"
    - "**/secrets/**"
  sanitize_logs: true
